version: "3.9"

services:
  news-parser-service: 
    build: .
    restart: "always"
    container_name: "news-parser-service"
    environment:
      - DB_USER=root
      - DB_PASSWORD=qweqweqwe
      - DB_HOST=db.server.orb.local
      - DB_PORT=5432
      - DB_NAME=database
    ports:
      - "9000:9000"